# Jekyll configuration for GitHub Pages
title: Olliter Manuals
description: Documentation and manuals for Olliter products
baseurl: "/Olliter"

markdown: GFM 
plugins:
- jekyll-gfm-admonitions
- jekyll-optional-front-matter

exclude: 
  - gemfiles/
  - Gemfile
  - Gemfile.lock
