# Jekyll configuration for GitHub Pages
title: Olliter Manuals
description: Documentation and manuals for Olliter products
website: https://olliter.github.io
basewebsite: /

markdown: GFM 
plugins:
- jekyll-gfm-admonitions
- jekyll-optional-front-matter

exclude: 
  - gemfiles/
  - Gemfile
  - Gemfile.lock
